version: '3.9'

services:
  investidor10:
    platform: linux/amd64
    build:
      context: .
    container_name: investidor10
    env_file:
      - .env
    restart: unless-stopped
    volumes:
      - .:/app
    working_dir: /app
    command: python -u main.py
    tty: true
    stdin_open: true
    ports:
      - "5000:5000"