version: '3.9'

services:
  investidor10-api:
    platform: linux/amd64
    build:
      context: .
    container_name: investidor10
    env_file:
      - .env 
    restart: unless-stopped
    volumes:
      - .:/app
    working_dir: /app
    tty: true
    stdin_open: true
    ports:
      - "${API_PORT}:5000"
